<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Review;

class ReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Using a collection to easily filter out duplicates by author.
        $reviews = collect([
            [
                'name' => 'cdyxxgfxzrxfcyc he u',
                'rate' => 5,
                'comment' => [
                    'ar' => 'مره حلو يختصر عليك جهد كبير 👍🏻 يعني بدال ما تبحث كل يوم عن مصطلحات جديده وتحاول تحفظها هو يقيس مستواك ويعطيك مصطلحات تناسب مستواك ويسوي لك عليها اختبار كل فتره شي جميل جدا انصح فيه بشده.',
                    'en' => 'Very nice, it saves you a lot of effort 👍🏻 I mean, instead of searching every day for new terms and trying to memorize them, it measures your level and gives you terms that suit your level and tests you on them every period. A very beautiful thing, I highly recommend it.',
                    'de' => 'Sehr schön, es erspart einem viel Mühe 👍🏻 Ich meine, anstatt jeden Tag nach neuen Begriffen zu suchen und zu versuchen, sie auswendig zu lernen, misst es Ihr Niveau und gibt Ihnen Begriffe, die zu Ihrem Niveau passen, und testet Sie in regelmäßigen Abständen darauf. Eine sehr schöne Sache, ich kann es nur wärmstens empfehlen.',
                    'el' => 'Πολύ ωραίο, σας γλιτώνει από πολύ κόπο 👍🏻 Δηλαδή, αντί να ψάχνετε κάθε μέρα για νέους όρους και να προσπαθείτε να τους απομνημονεύσετε, μετράει το επίπεδό σας και σας δίνει όρους που ταιριάζουν στο επίπεδό σας και σας εξετάζει σε αυτούς κάθε περίοδο. Ένα πολύ όμορφο πράγμα, το συνιστώ ανεπιφύλακτα.',
                    'es' => 'Muy bueno, te ahorra mucho esfuerzo 👍🏻 Es decir, en lugar de buscar cada día nuevos términos e intentar memorizarlos, mide tu nivel y te da términos que se ajustan a tu nivel y te pone a prueba sobre ellos cada cierto tiempo. Algo muy bonito, lo recomiendo encarecidamente.',
                    'fr' => 'Très sympa, ça vous évite beaucoup d\'efforts 👍🏻 Je veux dire, au lieu de chercher chaque jour de nouveaux termes et d\'essayer de les mémoriser, il mesure votre niveau et vous donne des termes qui correspondent à votre niveau et vous teste dessus à chaque période. Une très belle chose, je le recommande vivement.',
                    'it' => 'Molto bello, ti risparmia un sacco di fatica 👍🏻 Voglio dire, invece di cercare ogni giorno nuovi termini e cercare di memorizzarli, misura il tuo livello e ti dà termini adatti al tuo livello e ti mette alla prova su di essi ogni periodo. Una cosa molto bella, lo consiglio vivamente.',
                    'ja' => 'とても素敵で、多くの労力を節約できます👍🏻つまり、毎日新しい用語を検索して覚えようとする代わりに、あなたのレベルを測定し、あなたのレベルに合った用語を提供し、定期的にテストしてくれます。とても美しいもので、強くお勧めします。',
                    'ko' => '아주 좋습니다. 많은 노력을 덜어줍니다 👍🏻 매일 새로운 용어를 검색하고 암기하려고 노력하는 대신, 당신의 수준을 측정하고 당신의 수준에 맞는 용어를 제공하며 주기적으로 테스트합니다. 아주 아름다운 것이므로 강력히 추천합니다.',
                    'nl' => 'Erg fijn, het bespaart je veel moeite 👍🏻 Ik bedoel, in plaats van elke dag naar nieuwe termen te zoeken en te proberen ze te onthouden, meet het je niveau en geeft het je termen die bij je niveau passen en test het je er periodiek op. Iets heel moois, ik raad het ten zeerste aan.',
                    'pl' => 'Bardzo fajne, oszczędza mnóstwo wysiłku 👍🏻 To znaczy, zamiast codziennie szukać nowych terminów i próbować je zapamiętać, mierzy Twój poziom i podaje terminy pasujące do Twojego poziomu i okresowo Cię z nich testuje. Bardzo piękna rzecz, gorąco polecam.',
                    'pt' => 'Muito bom, poupa-lhe muito esforço 👍🏻 Quer dizer, em vez de procurar todos os dias por novos termos e tentar memorizá-los, ele mede o seu nível e dá-lhe termos que se adequam ao seu nível e testa-o neles a cada período. Uma coisa muito bonita, recomendo vivamente.',
                    'ru' => 'Очень приятно, это экономит вам много усилий 👍🏻 Я имею в виду, что вместо того, чтобы каждый день искать новые термины и пытаться их запомнить, он измеряет ваш уровень и дает вам термины, соответствующие вашему уровню, и периодически проверяет вас по ним. Очень красивая вещь, я настоятельно рекомендую.',
                    'tr' => 'Çok güzel, sizi büyük bir zahmetten kurtarıyor 👍🏻 Yani, her gün yeni terimler aramak ve ezberlemeye çalışmak yerine, seviyenizi ölçüyor ve seviyenize uygun terimler veriyor ve periyodik olarak sizi onlarla test ediyor. Çok güzel bir şey, şiddetle tavsiye ederim.',
                    'uk' => 'Дуже приємно, це економить вам багато зусиль 👍🏻 Я маю на увазі, що замість того, щоб щодня шукати нові терміни і намагатися їх запам\'ятати, він вимірює ваш рівень і дає вам терміни, які відповідають вашому рівню, і періодично перевіряє вас на них. Дуже гарна річ, я настійно рекомендую.',
                    'zh' => '非常好，为您节省了大量精力👍🏻我的意思是，它不是每天搜索新术语并试图记住它们，而是衡量您的水平，为您提供适合您水平的术语，并定期对您进行测试。一件非常美好的事情，我强烈推荐它。',
                ],
            ],
            [
                'name' => 'آلكربولي',
                'rate' => 5,
                'comment' => [
                    'ar' => 'وألله أفضل تطبيق لتعلم اللغة الانجليزية .أنصح به كل من يريد تعلم اللغة بسهولة و بتسلية🤩من الأخير تطبيق راقي والقائمين عليه أرقى😍اسأل الله أن يحفظكم ويوفقكم على هذه التحفة الجميلة. ويسدد خطاكم دائماً لتقديم الأفضل❤',
                    'en' => 'By God, the best application for learning the English language. I recommend it to everyone who wants to learn the language easily and with fun🤩. In short, a high-end application and the people in charge of it are even more so😍. I ask God to protect you and grant you success on this beautiful masterpiece. And may He always guide your steps to provide the best❤',
                    'de' => 'Bei Gott, die beste Anwendung zum Erlernen der englischen Sprache. Ich empfehle sie jedem, der die Sprache einfach und mit Spaß lernen möchte🤩. Kurz gesagt, eine High-End-Anwendung und die dafür Verantwortlichen sind es noch mehr😍. Ich bitte Gott, Sie zu beschützen und Ihnen Erfolg bei diesem wunderschönen Meisterwerk zu gewähren. Und möge Er Ihre Schritte immer leiten, um das Beste zu geben❤',
                    'el' => 'Μα τον Θεό, η καλύτερη εφαρμογή για την εκμάθηση της αγγλικής γλώσσας. Τη συνιστώ σε όλους όσους θέλουν να μάθουν τη γλώσσα εύκολα και με διασκέδαση🤩. Με λίγα λόγια, μια εφαρμογή υψηλών προδιαγραφών και οι υπεύθυνοι για αυτήν είναι ακόμα περισσότερο😍. Ζητώ από τον Θεό να σας προστατεύει και να σας χαρίσει επιτυχία σε αυτό το όμορφο αριστούργημα. Και μακάρι να καθοδηγεί πάντα τα βήματά σας για να παρέχετε το καλύτερο❤',
                    'es' => 'Por Dios, la mejor aplicación para aprender el idioma inglés. Se la recomiendo a todo el que quiera aprender el idioma fácilmente y con diversión🤩. En resumen, una aplicación de alta gama y las personas a cargo de ella lo son aún más😍. Le pido a Dios que los proteja y les conceda el éxito en esta hermosa obra maestra. Y que Él siempre guíe sus pasos para ofrecer lo mejor❤',
                    'fr' => 'Par Dieu, la meilleure application pour apprendre la langue anglaise. Je la recommande à tous ceux qui veulent apprendre la langue facilement et en s\'amusant🤩. En bref, une application haut de gamme et les personnes qui en sont responsables le sont encore plus😍. Je demande à Dieu de vous protéger et de vous accorder le succès sur ce magnifique chef-d\'œuvre. Et qu\'Il guide toujours vos pas pour fournir le meilleur❤',
                    'it' => 'Per Dio, la migliore applicazione per imparare la lingua inglese. La consiglio a tutti coloro che vogliono imparare la lingua facilmente e divertendosi🤩. In breve, un\'applicazione di alto livello e le persone che se ne occupano lo sono ancora di più😍. Chiedo a Dio di proteggervi e di concedervi il successo in questo bellissimo capolavoro. E che Egli guidi sempre i vostri passi per fornire il meglio❤',
                    'ja' => '神にかけて、英語を学ぶのに最適なアプリケーションです。簡単かつ楽しく言語を学びたいすべての人にお勧めします🤩。要するに、ハイエンドなアプリケーションであり、その担当者はさらにそうです😍。この美しい傑作であなたを守り、成功させてくださるよう神にお願いします。そして、彼が常にあなたの歩みを導き、最高のものを提供してくださいますように❤',
                    'ko' => '맙소사, 최고의 영어 학습 앱입니다. 쉽고 재미있게 언어를 배우고 싶은 모든 사람에게 추천합니다🤩. 요컨대, 고급 응용 프로그램이며 담당자는 더욱 그렇습니다😍. 이 아름다운 걸작에 대해 신께서 당신을 보호하고 성공을 허락하시기를 간구합니다. 그리고 그분께서 항상 당신의 발걸음을 인도하여 최고를 제공하시기를 바랍니다❤',
                    'nl' => 'Bij God, de beste applicatie om de Engelse taal te leren. Ik raad het iedereen aan die de taal gemakkelijk en met plezier wil leren🤩. Kortom, een high-end applicatie en de mensen die er verantwoordelijk voor zijn, zijn dat nog meer😍. Ik vraag God om u te beschermen en u succes te schenken met dit prachtige meesterwerk. En moge Hij uw stappen altijd leiden om het beste te bieden❤',
                    'pl' => 'Na Boga, najlepsza aplikacja do nauki języka angielskiego. Polecam ją każdemu, kto chce łatwo i z przyjemnością uczyć się języka🤩. Krótko mówiąc, aplikacja z wyższej półki, a osoby za nią odpowiedzialne jeszcze bardziej😍. Proszę Boga, aby cię chronił i obdarzył sukcesem w tym pięknym arcydziele. I niech zawsze kieruje twoimi krokami, aby zapewnić to, co najlepsze❤',
                    'pt' => 'Por Deus, a melhor aplicação para aprender a língua inglesa. Recomendo-a a todos os que queiram aprender a língua facilmente e com diversão🤩. Em suma, uma aplicação de topo e as pessoas responsáveis por ela são-no ainda mais😍. Peço a Deus que vos proteja e vos conceda sucesso nesta bela obra-prima. E que Ele guie sempre os vossos passos para oferecer o melhor❤',
                    'ru' => 'Ей-богу, лучшее приложение для изучения английского языка. Я рекомендую его всем, кто хочет легко и с удовольствием изучать язык🤩. Короче говоря, это первоклассное приложение, а люди, отвечающие за него, еще лучше😍. Я прошу Бога защитить вас и даровать вам успех в этом прекрасном шедевре. И пусть Он всегда направляет ваши шаги, чтобы вы могли дать лучшее❤',
                    'tr' => 'Allah aşkına, İngilizce öğrenmek için en iyi uygulama. Dili kolayca ve eğlenerek öğrenmek isteyen herkese tavsiye ederim🤩. Kısacası, üst düzey bir uygulama ve ondan sorumlu olanlar daha da fazlası😍. Tanrı\'dan sizi korumasını ve bu güzel başyapıtta size başarı vermesini diliyorum. Ve adımlarınızı her zaman en iyisini sunmak için yönlendirsin❤',
                    'uk' => 'Боже, найкращий додаток для вивчення англійської мови. Я рекомендую його всім, хто хоче вивчати мову легко і з задоволенням🤩. Коротше кажучи, це висококласний додаток, а люди, які за нього відповідають, ще кращі😍. Я прошу Бога захистити вас і дарувати вам успіх у цьому прекрасному шедеврі. І нехай Він завжди направляє ваші кроки, щоб ви могли дати найкраще❤',
                    'zh' => '天哪，学习英语的最佳应用程序。我向每个想轻松有趣地学习语言的人推荐它🤩。简而言之，一个高端的应用程序，负责它的人更是如此😍。我祈求上帝保佑您，并在这部美丽的杰作上赐予您成功。愿他永远指引您的脚步，提供最好的❤',
                ],
            ],
            [
                'name' => 'aloo134',
                'rate' => 5,
                'comment' => [
                    'ar' => 'أستمتع بقراءة القصص والاستماع إليها وبساطة التطبيق ؟؟؟؟',
                    'en' => 'I enjoy reading & listening to the stories and the simplicity of the app ????',
                    'de' => 'Ich genieße es, die Geschichten zu lesen und anzuhören und die Einfachheit der App ????',
                    'el' => 'Μου αρέσει να διαβάζω και να ακούω τις ιστορίες και την απλότητα της εφαρμογής ????',
                    'es' => 'Disfruto leyendo y escuchando las historias y la simplicidad de la aplicación ????',
                    'fr' => 'J\'aime lire et écouter les histoires et la simplicité de l\'application ????',
                    'it' => 'Mi piace leggere e ascoltare le storie e la semplicità dell\'app ????',
                    'ja' => '物語を読んだり聞いたり、アプリのシンプルさを楽しんでいます????',
                    'ko' => '저는 이야기를 읽고 듣는 것과 앱의 단순함을 즐깁니다 ????',
                    'nl' => 'Ik geniet van het lezen en luisteren naar de verhalen en de eenvoud van de app ????',
                    'pl' => 'Lubię czytać i słuchać opowieści oraz prostotę aplikacji ????',
                    'pt' => 'Eu gosto de ler e ouvir as histórias e a simplicidade do aplicativo ????',
                    'ru' => 'Мне нравится читать и слушать истории, а также простота приложения ????',
                    'tr' => 'Hikayeleri okumayı ve dinlemeyi ve uygulamanın basitliğini seviyorum ????',
                    'uk' => 'Мені подобається читати та слухати історії, а також простота додатка ????',
                    'zh' => '我喜欢阅读和聆听故事以及这个应用程序的简洁性????',
                ],
            ],
            [
                'name' => 'pinkwatter',
                'rate' => 5,
                'comment' => [
                    'ar' => 'القصص جميلة وفي مراجعة الكلمات للتدرب',
                    'en' => 'The stories are beautiful and there is a review of words to practice.',
                    'de' => 'Die Geschichten sind wunderschön und es gibt eine Wiederholung von Wörtern zum Üben.',
                    'el' => 'Οι ιστορίες είναι όμορφες και υπάρχει μια ανασκόπηση των λέξεων για εξάσκηση.',
                    'es' => 'Las historias son hermosas y hay un repaso de palabras para practicar.',
                    'fr' => 'Les histoires sont belles et il y a une révision des mots pour s\'entraîner.',
                    'it' => 'Le storie sono bellissime e c\'è una revisione delle parole per esercitarsi.',
                    'ja' => '物語は美しく、練習用の単語の復習があります。',
                    'ko' => '이야기는 아름답고 연습할 단어 복습이 있습니다.',
                    'nl' => 'De verhalen zijn prachtig en er is een herhaling van woorden om te oefenen.',
                    'pl' => 'Historie są piękne i jest powtórka słów do ćwiczenia.',
                    'pt' => 'As histórias são lindas e há uma revisão de palavras para praticar.',
                    'ru' => 'Истории прекрасны, и есть повторение слов для практики.',
                    'tr' => 'Hikayeler güzel ve pratik yapmak için kelimelerin bir tekrarı var.',
                    'uk' => 'Історії прекрасні, і є повторення слів для практики.',
                    'zh' => '故事很美，还有单词复习供练习。',
                ],
            ],
            [
                'name' => 'saleh7007',
                'rate' => 5,
                'comment' => [
                    'ar' => 'جدا مفيد وللاستفاده اكثر مراجعة القصة وقراءتها دون المساعدة للامانه استفدت كثير والقادم افضل',
                    'en' => 'Very useful, and for more benefit, review the story and read it without assistance. Honestly, I benefited a lot and the future is better.',
                    'de' => 'Sehr nützlich, und für mehr Nutzen, wiederholen Sie die Geschichte und lesen Sie sie ohne Hilfe. Ehrlich gesagt, habe ich viel profitiert und die Zukunft ist besser.',
                    'el' => 'Πολύ χρήσιμο, και για περισσότερο όφελος, αναθεωρήστε την ιστορία και διαβάστε την χωρίς βοήθεια. Ειλικρινά, ωφελήθηκα πολύ και το μέλλον είναι καλύτερο.',
                    'es' => 'Muy útil, y para mayor beneficio, repasa la historia y léela sin ayuda. Honestamente, me beneficié mucho y el futuro es mejor.',
                    'fr' => 'Très utile, et pour plus de bénéfices, révisez l\'histoire et lisez-la sans aide. Honnêtement, j\'ai beaucoup profité et l\'avenir est meilleur.',
                    'it' => 'Molto utile, e per maggiori benefici, ripassa la storia e leggila senza assistenza. Onestamente, ne ho tratto molto beneficio e il futuro è migliore.',
                    'ja' => '非常に便利で、さらに多くの利益を得るために、物語を復習し、助けなしで読んでください。正直なところ、私は多くの恩恵を受け、未来はより良いです。',
                    'ko' => '매우 유용하며, 더 많은 이점을 위해 이야기를 복습하고 도움 없이 읽으십시오. 솔직히, 저는 많은 혜택을 받았고 미래는 더 좋습니다.',
                    'nl' => 'Zeer nuttig, en voor meer voordeel, herzie het verhaal en lees het zonder hulp. Eerlijk gezegd heb ik er veel baat bij gehad en de toekomst is beter.',
                    'pl' => 'Bardzo przydatne, a dla większych korzyści, przejrzyj historię i przeczytaj ją bez pomocy. Szczerze mówiąc, bardzo skorzystałem, a przyszłość jest lepsza.',
                    'pt' => 'Muito útil, e para mais benefícios, revise a história e leia-a sem ajuda. Honestamente, beneficiei muito e o futuro é melhor.',
                    'ru' => 'Очень полезно, и для большей пользы, просмотрите историю и прочитайте ее без помощи. Честно говоря, я получил много пользы, и будущее лучше.',
                    'tr' => 'Çok faydalı ve daha fazla fayda için hikayeyi gözden geçirin ve yardım almadan okuyun. Dürüst olmak gerekirse, çok fayda sağladım ve gelecek daha iyi.',
                    'uk' => 'Дуже корисно, і для більшої користі, перегляньте історію і прочитайте її без допомоги. Чесно кажучи, я отримав багато користі, і майбутнє краще.',
                    'zh' => '非常有用，为了获得更多好处，请复习故事并在没有帮助的情况下阅读。老实说，我受益匪浅，未来会更好。',
                ],
            ],
            [
                'name' => 'بو مضاوي',
                'rate' => 5,
                'comment' => [
                    'ar' => 'جدا مفيد لتحسين اللغة الانجليزية ويعطيك اختبارات واهداف يومية',
                    'en' => 'Very useful for improving the English language and it gives you daily tests and goals.',
                    'de' => 'Sehr nützlich zur Verbesserung der englischen Sprache und es gibt Ihnen tägliche Tests und Ziele.',
                    'el' => 'Πολύ χρήσιμο για τη βελτίωση της αγγλικής γλώσσας και σας δίνει καθημερινά τεστ και στόχους.',
                    'es' => 'Muy útil para mejorar el idioma inglés y te da pruebas y metas diarias.',
                    'fr' => 'Très utile pour améliorer la langue anglaise et il vous donne des tests et des objectifs quotidiens.',
                    'it' => 'Molto utile per migliorare la lingua inglese e ti dà test e obiettivi giornalieri.',
                    'ja' => '英語を上達させるのに非常に便利で、毎日のテストと目標を提供します。',
                    'ko' => '영어 실력 향상에 매우 유용하며 매일 테스트와 목표를 제공합니다.',
                    'nl' => 'Zeer nuttig voor het verbeteren van de Engelse taal en het geeft je dagelijkse tests en doelen.',
                    'pl' => 'Bardzo przydatne do poprawy języka angielskiego i daje codzienne testy i cele.',
                    'pt' => 'Muito útil para melhorar o idioma inglês e dá-lhe testes e metas diárias.',
                    'ru' => 'Очень полезно для улучшения английского языка и дает вам ежедневные тесты и цели.',
                    'tr' => 'İngilizce dilini geliştirmek için çok faydalıdır ve size günlük testler ve hedefler verir.',
                    'uk' => 'Дуже корисно для покращення англійської мови, і це дає вам щоденні тести та цілі.',
                    'zh' => '对于提高英语水平非常有用，它为您提供每日测试和目标。',
                ],
            ],
            [
                'name' => 'خولة',
                'rate' => 5,
                'comment' => [
                    'ar' => 'أتعب وأنا أقول رهيب على كثر التطبيقات إلي حملتها عشان أتعلم بس ذا كان أفضلهم حسيت أن مستواي فعلاً جالس يتطور مو مثل قبل حسيت أني استمتع وأنا أتعلم وصرت منتظمة يومياً عليه .. طبعاً أخذت فترة تجريبية وما كنت متوقعة أني راح أشترك بس بعد الفترة التجريبية تحمست واشتركت وكان هذا أول برنامج أشترك فيه … شكراً من القلب للي قائمين على البرنامج ??❤️❤️',
                    'en' => 'I get tired of saying it\'s amazing. Among the many applications I downloaded to learn, this was the best. I felt that my level was actually developing, not like before. I felt that I enjoyed learning and I became regular on it daily.. Of course, I took a trial period and I did not expect to subscribe, but after the trial period I got excited and subscribed and this was the first program I subscribed to... Thank you from the bottom of my heart to those in charge of the program ??❤️❤️',
                    'de' => 'Ich werde müde zu sagen, dass es erstaunlich ist. Unter den vielen Anwendungen, die ich zum Lernen heruntergeladen habe, war dies die beste. Ich hatte das Gefühl, dass sich mein Niveau tatsächlich weiterentwickelte, nicht wie zuvor. Ich hatte das Gefühl, dass ich das Lernen genoss und ich wurde täglich regelmäßig darin. Natürlich habe ich eine Probezeit genommen und nicht erwartet, mich anzumelden, aber nach der Probezeit war ich begeistert und habe mich angemeldet und dies war das erste Programm, das ich abonniert habe... Vielen Dank von ganzem Herzen an die Verantwortlichen des Programms ??❤️❤️',
                    'el' => 'Κουράζομαι να λέω ότι είναι καταπληκτικό. Ανάμεσα στις πολλές εφαρμογές που κατέβασα για να μάθω, αυτή ήταν η καλύτερη. Ένιωσα ότι το επίπεδό μου όντως εξελισσόταν, όχι όπως πριν. Ένιωσα ότι απολάμβανα τη μάθηση και έγινα τακτικός σε αυτήν καθημερινά.. Φυσικά, πήρα μια δοκιμαστική περίοδο και δεν περίμενα να εγγραφώ, αλλά μετά τη δοκιμαστική περίοδο ενθουσιάστηκα και εγγράφηκα και αυτό ήταν το πρώτο πρόγραμμα στο οποίο εγγράφηκα... Σας ευχαριστώ από τα βάθη της καρδιάς μου στους υπεύθυνους του προγράμματος ??❤️❤️',
                    'es' => 'Me canso de decir que es increíble. Entre las muchas aplicaciones que descargué para aprender, esta fue la mejor. Sentí que mi nivel se estaba desarrollando de verdad, no como antes. Sentí que disfrutaba aprendiendo y me volví regular en ello a diario... Por supuesto, tomé un período de prueba y no esperaba suscribirme, pero después del período de prueba me emocioné y me suscribí y este fue el primer programa al que me suscribí... Gracias desde el fondo de mi corazón a los responsables del programa ??❤️❤️',
                    'fr' => 'Je me lasse de dire que c\'est incroyable. Parmi les nombreuses applications que j\'ai téléchargées pour apprendre, celle-ci était la meilleure. J\'ai senti que mon niveau se développait réellement, pas comme avant. J\'ai senti que j\'aimais apprendre et je suis devenu régulier dessus quotidiennement.. Bien sûr, j\'ai pris une période d\'essai et je ne m\'attendais pas à m\'abonner, mais après la période d\'essai, je me suis enthousiasmé et je me suis abonné et c\'était le premier programme auquel je me suis abonné... Merci du fond du cœur aux responsables du programme ??❤️❤️',
                    'it' => 'Mi stanco di dire che è fantastico. Tra le tante applicazioni che ho scaricato per imparare, questa è stata la migliore. Sentivo che il mio livello si stava effettivamente sviluppando, non come prima. Sentivo che mi piaceva imparare e sono diventato regolare su di esso ogni giorno.. Certo, ho fatto un periodo di prova e non mi aspettavo di iscrivermi, ma dopo il periodo di prova mi sono entusiasmato e mi sono iscritto e questo è stato il primo programma a cui mi sono iscritto... Grazie dal profondo del mio cuore a coloro che sono responsabili del programma ??❤️❤️',
                    'ja' => 'すごいと言い飽きました。私が学習するためにダウンロードした多くのアプリケーションの中で、これが最高でした。以前とは違い、私のレベルは実際に向上していると感じました。学習を楽しんでいると感じ、毎日定期的にそれに取り組むようになりました。もちろん、試用期間を取り、購読するとは思っていませんでしたが、試用期間の後、興奮して購読し、これが私が購読した最初のプログラムでした...プログラムの責任者の方々に心から感謝します??❤️❤️',
                    'ko' => '놀랍다고 말하기 지겹습니다. 배우기 위해 다운로드한 많은 응용 프로그램 중에서 이것이 최고였습니다. 예전과 달리 제 수준이 실제로 발전하고 있다고 느꼈습니다. 배우는 것을 즐기고 매일 꾸준히 하게 되었습니다. 물론, 저는 시험 기간을 가졌고 구독할 것이라고 기대하지 않았지만, 시험 기간 후에 흥분해서 구독했고 이것이 제가 구독한 첫 번째 프로그램이었습니다... 프로그램 책임자 분들께 진심으로 감사드립니다 ??❤️❤️',
                    'nl' => 'Ik word er moe van om te zeggen dat het geweldig is. Van de vele applicaties die ik heb gedownload om te leren, was dit de beste. Ik voelde dat mijn niveau zich daadwerkelijk ontwikkelde, niet zoals voorheen. Ik voelde dat ik het leuk vond om te leren en ik werd er dagelijks regelmatig in.. Natuurlijk nam ik een proefperiode en ik had niet verwacht me te abonneren, maar na de proefperiode raakte ik enthousiast en abonneerde ik me en dit was het eerste programma waarop ik me abonneerde... Dank u uit de grond van mijn hart aan degenen die verantwoordelijk zijn voor het programma ??❤️❤️',
                    'pl' => 'Męczy mnie mówienie, że to niesamowite. Spośród wielu aplikacji, które pobrałem, aby się uczyć, ta była najlepsza. Czułem, że mój poziom faktycznie się rozwija, nie tak jak wcześniej. Czułem, że lubię się uczyć i stałem się w tym regularny codziennie.. Oczywiście, wziąłem okres próbny i nie spodziewałem się, że zasubskrybuję, ale po okresie próbnym podekscytowałem się i zasubskrybowałem, i to był pierwszy program, który zasubskrybowałem... Dziękuję z głębi serca osobom odpowiedzialnym za program ??❤️❤️',
                    'pt' => 'Canso-me de dizer que é incrível. Entre as muitas aplicações que descarreguei para aprender, esta foi a melhor. Senti que o meu nível estava realmente a desenvolver-se, não como antes. Senti que gostava de aprender e tornei-me regular nisso diariamente.. Claro, fiz um período experimental e não esperava subscrever, mas depois do período experimental fiquei entusiasmado e subscrevi e este foi o primeiro programa que subscrevi... Obrigado do fundo do meu coração aos responsáveis pelo programa ??❤️❤️',
                    'ru' => 'Я устаю говорить, что это потрясающе. Среди множества приложений, которые я скачал для обучения, это было лучшее. Я чувствовал, что мой уровень действительно развивается, не так, как раньше. Я чувствовал, что мне нравится учиться, и я стал регулярно заниматься этим ежедневно.. Конечно, я взял пробный период и не ожидал, что подпишусь, но после пробного периода я пришел в восторг и подписался, и это была первая программа, на которую я подписался... Спасибо от всего сердца тем, кто отвечает за программу ??❤️❤️',
                    'tr' => 'Harika olduğunu söylemekten yoruldum. Öğrenmek için indirdiğim birçok uygulama arasında bu en iyisiydi. Seviyemin eskisi gibi olmadığını, gerçekten geliştiğini hissettim. Öğrenmekten zevk aldığımı hissettim ve her gün düzenli olarak kullanmaya başladım.. Tabii ki, bir deneme süresi aldım ve abone olmayı beklemiyordum, ancak deneme süresinden sonra heyecanlandım ve abone oldum ve bu abone olduğum ilk programdı... Programdan sorumlu olanlara kalbimin derinliklerinden teşekkür ederim ??❤️❤️',
                    'uk' => 'Я втомлююся говорити, що це дивовижно. Серед багатьох програм, які я завантажив для навчання, ця була найкращою. Я відчував, що мій рівень насправді розвивається, не так, як раніше. Я відчував, що мені подобається вчитися, і я став регулярно займатися цим щодня.. Звичайно, я взяв пробний період і не очікував, що підпишуся, але після пробного періоду я захопився і підписався, і це була перша програма, на яку я підписався... Дякую від щирого серця тим, хто відповідає за програму ??❤️❤️',
                    'zh' => '我说它很棒都说累了。在我下载的许多学习应用程序中，这是最好的。我觉得我的水平确实在发展，不像以前。我觉得我喜欢学习，并且每天都坚持使用它。当然，我试用了一段时间，并没有期望订阅，但在试用期结束后，我感到很兴奋并订阅了，这是我订阅的第一个程序......我衷心感谢负责该程序的人??❤️❤️',
                ],
            ],
            [
                'name' => 'أبو جبرة',
                'rate' => 5,
                'comment' => [
                    'ar' => 'تطبيق ممتاز جدا في قراءة النص باللغة الانجليزية والاستماع له ويساعد على الحفظ',
                    'en' => 'An excellent application for reading the text in English and listening to it, and it helps with memorization.',
                    'de' => 'Eine ausgezeichnete Anwendung zum Lesen des Textes auf Englisch und zum Anhören, und sie hilft beim Auswendiglernen.',
                    'el' => 'Μια εξαιρετική εφαρμογή για την ανάγνωση του κειμένου στα αγγλικά και την ακρόασή του, και βοηθά στην απομνημόνευση.',
                    'es' => 'Una excelente aplicación para leer el texto en inglés y escucharlo, y ayuda a la memorización.',
                    'fr' => 'Une excellente application pour lire le texte en anglais et l\'écouter, et elle aide à la mémorisation.',
                    'it' => 'Un\'applicazione eccellente per leggere il testo in inglese e ascoltarlo, e aiuta con la memorizzazione.',
                    'ja' => '英語のテキストを読んだり聞いたりするのに優れたアプリケーションで、暗記に役立ちます。',
                    'ko' => '영어로 텍스트를 읽고 듣는 데 훌륭한 응용 프로그램이며 암기에 도움이 됩니다.',
                    'nl' => 'Een uitstekende applicatie voor het lezen van de tekst in het Engels en het luisteren ernaar, en het helpt bij het onthouden.',
                    'pl' => 'Doskonała aplikacja do czytania tekstu w języku angielskim i słuchania go, i pomaga w zapamiętywaniu.',
                    'pt' => 'Uma excelente aplicação para ler o texto em inglês e ouvi-lo, e ajuda na memorização.',
                    'ru' => 'Отличное приложение для чтения текста на английском языке и его прослушивания, и оно помогает с запоминанием.',
                    'tr' => 'İngilizce metni okumak ve dinlemek için mükemmel bir uygulama ve ezberlemeye yardımcı olur.',
                    'uk' => 'Відмінний додаток для читання тексту англійською мовою та його прослуховування, і це допомагає із запам\'ятовуванням.',
                    'zh' => '一个用于阅读和听英语文本的优秀应用程序，它有助于记忆。',
                ],
            ],
            [
                'name' => 'أنوار هنية',
                'rate' => 5,
                'comment' => [
                    'ar' => 'تطبيق راااااائع وممتع خصوصا بعد التحديثات الأخيرة والمميزات الجديدة. أنصح به.',
                    'en' => 'A wonderful and enjoyable application, especially after the recent updates and new features. I recommend it.',
                    'de' => 'Eine wunderbare und unterhaltsame Anwendung, besonders nach den letzten Updates und neuen Funktionen. Ich empfehle sie.',
                    'el' => 'Μια υπέροχη και απολαυστική εφαρμογή, ειδικά μετά τις πρόσφατες ενημερώσεις και τα νέα χαρακτηριστικά. Τη συνιστώ.',
                    'es' => 'Una aplicación maravillosa y agradable, especialmente después de las recientes actualizaciones y nuevas características. La recomiendo.',
                    'fr' => 'Une application merveilleuse et agréable, surtout après les récentes mises à jour et les nouvelles fonctionnalités. Je la recommande.',
                    'it' => 'Un\'applicazione meravigliosa e piacevole, soprattutto dopo i recenti aggiornamenti e le nuove funzionalità. La consiglio.',
                    'ja' => '最近のアップデートと新機能の後、特に素晴らしい楽しいアプリケーションです。お勧めします。',
                    'ko' => '최근 업데이트와 새로운 기능 이후 특히 훌륭하고 즐거운 응용 프로그램입니다. 추천합니다.',
                    'nl' => 'Een prachtige en plezierige applicatie, vooral na de recente updates en nieuwe functies. Ik raad het aan.',
                    'pl' => 'Wspaniała i przyjemna aplikacja, zwłaszcza po ostatnich aktualizacjach i nowych funkcjach. Polecam ją.',
                    'pt' => 'Uma aplicação maravilhosa e agradável, especialmente após as recentes atualizações e novas funcionalidades. Recomendo-a.',
                    'ru' => 'Замечательное и приятное приложение, особенно после последних обновлений и новых функций. Я рекомендую его.',
                    'tr' => 'Özellikle son güncellemeler ve yeni özelliklerden sonra harika ve keyifli bir uygulama. Tavsiye ederim.',
                    'uk' => 'Чудовий і приємний додаток, особливо після останніх оновлень та нових функцій. Я рекомендую його.',
                    'zh' => '一个精彩而有趣的应用程序，尤其是在最近的更新和新功能之后。我推荐它。',
                ],
            ],
            [
                'name' => 'Profess Or',
                'rate' => 5,
                'comment' => [
                    'ar' => 'برنامج رائع ومستوياته مذهله',
                    'en' => 'A wonderful program and its levels are amazing.',
                    'de' => 'Ein wunderbares Programm und seine Level sind erstaunlich.',
                    'el' => 'Ένα υπέροχο πρόγραμμα και τα επίπεδά του είναι εκπληκτικά.',
                    'es' => 'Un programa maravilloso y sus niveles son asombrosos.',
                    'fr' => 'Un programme merveilleux et ses niveaux sont incroyables.',
                    'it' => 'Un programma meraviglioso e i suoi livelli sono sorprendenti.',
                    'ja' => '素晴らしいプログラムで、そのレベルは驚くべきものです。',
                    'ko' => '훌륭한 프로그램이며 그 수준은 놀랍습니다.',
                    'nl' => 'Een prachtig programma en de niveaus zijn geweldig.',
                    'pl' => 'Wspaniały program, a jego poziomy są niesamowite.',
                    'pt' => 'Um programa maravilhoso e os seus níveis são incríveis.',
                    'ru' => 'Замечательная программа, и ее уровни потрясающие.',
                    'tr' => 'Harika bir program ve seviyeleri inanılmaz.',
                    'uk' => 'Чудова програма, і її рівні дивовижні.',
                    'zh' => '一个很棒的程序，它的水平令人惊叹。',
                ],
            ],
             [
                'name' => 'عبدالرحمن',
                'rate' => 5,
                'comment' => [
                    'ar' => 'تطبيق محترم ونظيف وواضح وسلس وبدون تعقيد .. احترافي حقا',
                    'en' => 'A respectable, clean, clear, smooth, and uncomplicated application... truly professional.',
                    'de' => 'Eine respektable, saubere, klare, reibungslose und unkomplizierte Anwendung... wirklich professionell.',
                    'el' => 'Μια αξιοσέβαστη, καθαρή, σαφής, ομαλή και απλή εφαρμογή... πραγματικά επαγγελματική.',
                    'es' => 'Una aplicación respetable, limpia, clara, fluida y sin complicaciones... verdaderamente profesional.',
                    'fr' => 'Une application respectable, propre, claire, fluide et simple... vraiment professionnelle.',
                    'it' => 'Un\'applicazione rispettabile, pulita, chiara, fluida e senza complicazioni... veramente professionale.',
                    'ja' => '尊敬できる、クリーンで、クリアで、スムーズで、複雑でないアプリケーション...本当にプロフェッショナルです。',
                    'ko' => '존경할 만하고, 깨끗하고, 명확하고, 부드럽고, 복잡하지 않은 응용 프로그램... 진정으로 전문적입니다.',
                    'nl' => 'Een respectabele, schone, duidelijke, soepele en ongecompliceerde applicatie... echt professioneel.',
                    'pl' => 'Szanowana, czysta, przejrzysta, płynna i nieskomplikowana aplikacja... naprawdę profesjonalna.',
                    'pt' => 'Uma aplicação respeitável, limpa, clara, suave e descomplicada... verdadeiramente profissional.',
                    'ru' => 'Респектабельное, чистое, понятное, гладкое и несложное приложение... поистине профессиональное.',
                    'tr' => 'Saygın, temiz, anlaşılır, sorunsuz ve karmaşık olmayan bir uygulama... gerçekten profesyonel.',
                    'uk' => 'Поважна, чиста, зрозуміла, гладка і нескладна програма... справді професійна.',
                    'zh' => '一个体面、干净、清晰、流畅且不复杂的应用程序......真正专业。',
                ],
            ],
            [
                'name' => 'Saadx_ 7',
                'rate' => 5,
                'comment' => [
                    'ar' => 'تطبيق في منتهى الروعة تطورت لغتي الإنجليزية بشكل جبار اشكر كل القائمين على هذا التطبيق الرائع ?❤️ امسكوا ورده هدية ??.',
                    'en' => 'An application of the utmost magnificence. My English has developed immensely. I thank everyone in charge of this wonderful application ?❤️ Here, take a rose as a gift ??.',
                    'de' => 'Eine Anwendung von höchster Pracht. Mein Englisch hat sich immens entwickelt. Ich danke allen, die für diese wunderbare Anwendung verantwortlich sind ?❤️ Hier, nimm eine Rose als Geschenk ??.',
                    'el' => 'Μια εφαρμογή υψίστης μεγαλοπρέπειας. Τα αγγλικά μου έχουν αναπτυχθεί πάρα πολύ. Ευχαριστώ όλους τους υπεύθυνους για αυτήν την υπέροχη εφαρμογή ?❤️ Ορίστε, πάρτε ένα τριαντάφυλλο για δώρο ??.',
                    'es' => 'Una aplicación de la máxima magnificencia. Mi inglés se ha desarrollado inmensamente. Agradezco a todos los responsables de esta maravillosa aplicación ?❤️ Toma, una rosa de regalo ??.',
                    'fr' => 'Une application de la plus grande magnificence. Mon anglais s\'est immensément développé. Je remercie tous les responsables de cette merveilleuse application ?❤️ Tenez, prenez une rose en cadeau ??.',
                    'it' => 'Un\'applicazione della massima magnificenza. Il mio inglese si è sviluppato immensamente. Ringrazio tutti i responsabili di questa meravigliosa applicazione ?❤️ Tieni, prendi una rosa in regalo ??.',
                    'ja' => '最高に素晴らしいアプリケーションです。私の英語は非常に上達しました。この素晴らしいアプリケーションの担当者全員に感謝します?❤️どうぞ、贈り物としてバラをどうぞ??。',
                    'ko' => '최고의 웅장함을 자랑하는 애플리케이션입니다. 제 영어 실력이 엄청나게 향상되었습니다. 이 훌륭한 애플리케이션을 책임지는 모든 분들께 감사드립니다 ?❤️ 여기 선물로 장미를 받으세요 ??.',
                    'nl' => 'Een toepassing van de allergrootste pracht. Mijn Engels heeft zich enorm ontwikkeld. Ik dank iedereen die verantwoordelijk is voor deze prachtige toepassing ?❤️ Hier, neem een roos als geschenk ??.',
                    'pl' => 'Aplikacja o najwyższym wspaniałości. Mój angielski ogromnie się rozwinął. Dziękuję wszystkim odpowiedzialnym za tę wspaniałą aplikację ?❤️ Proszę, weź różę w prezencie ??.',
                    'pt' => 'Uma aplicação da máxima magnificência. O meu inglês desenvolveu-se imensamente. Agradeço a todos os responsáveis por esta maravilhosa aplicação ?❤️ Toma, uma rosa de presente ??.',
                    'ru' => 'Приложение величайшего великолепия. Мой английский очень сильно развился. Я благодарю всех, кто отвечает за это замечательное приложение ?❤️ Вот, возьмите розу в подарок ??.',
                    'tr' => 'En üst düzeyde ihtişamlı bir uygulama. İngilizcem çok gelişti. Bu harika uygulamanın sorumlu olan herkese teşekkür ederim ?❤️ Alın, hediye olarak bir gül ??.',
                    'uk' => 'Додаток надзвичайної пишності. Моя англійська надзвичайно розвинулася. Я дякую всім, хто відповідає за цей чудовий додаток ?❤️ Ось, візьміть троянду в подарунок ??.',
                    'zh' => '一个极其宏伟的应用程序。我的英语水平得到了极大的发展。我感谢负责这个精彩应用程序的每一个人 ?❤️ 来，收下一朵玫瑰作为礼物 ??。',
                ],
            ],
            [
                'name' => 'عبدالمحسن الجابري',
                'rate' => 5,
                'comment' => [
                    'ar' => 'ممتاز ومفيد جداً وتعلم بأسهل وأسرع الطرق وبأقل تكلفه ???',
                    'en' => 'Excellent and very useful, and learning in the easiest and fastest ways and at the lowest cost ???',
                    'de' => 'Ausgezeichnet und sehr nützlich, und Lernen auf die einfachste und schnellste Weise und zu den niedrigsten Kosten ???',
                    'el' => 'Εξαιρετικό και πολύ χρήσιμο, και μάθηση με τον ευκολότερο και ταχύτερο τρόπο και με το χαμηλότερο κόστος ???',
                    'es' => 'Excelente y muy útil, y aprender de la manera más fácil y rápida y al menor costo ???',
                    'fr' => 'Excellent et très utile, et apprendre de la manière la plus simple et la plus rapide et au moindre coût ???',
                    'it' => 'Eccellente e molto utile, e imparare nel modo più facile e veloce e al minor costo ???',
                    'ja' => '非常に優れており、非常に便利で、最も簡単で最速の方法で、最低のコストで学習できます???',
                    'ko' => '훌륭하고 매우 유용하며 가장 쉽고 빠른 방법으로 가장 저렴한 비용으로 학습할 수 있습니다 ???',
                    'nl' => 'Uitstekend en zeer nuttig, en leren op de gemakkelijkste en snelste manier en tegen de laagste kosten ???',
                    'pl' => 'Doskonały i bardzo przydatny, a nauka w najłatwiejszy i najszybszy sposób i po najniższych kosztach ???',
                    'pt' => 'Excelente e muito útil, e aprender da maneira mais fácil e rápida e com o menor custo ???',
                    'ru' => 'Отлично и очень полезно, и обучение самыми простыми и быстрыми способами и по самой низкой цене ???',
                    'tr' => 'Mükemmel ve çok kullanışlı, en kolay ve en hızlı yollarla ve en düşük maliyetle öğrenme ???',
                    'uk' => 'Відмінно і дуже корисно, і навчання найпростішими і найшвидшими способами і за найнижчою вартістю ???',
                    'zh' => '优秀且非常有用，以最简单、最快的方式、以最低的成本学习 ???',
                ],
            ],
            [
                'name' => 'عبدالاله محمد',
                'rate' => 5,
                'comment' => [
                    'ar' => 'بصراحه أكثر من رائع ممتاز مفيييييد',
                    'en' => 'Honestly more than wonderful, excellent, and usefuuuul.',
                    'de' => 'Ehrlich gesagt mehr als wunderbar, ausgezeichnet und nützliiiich.',
                    'el' => 'Ειλικρινά περισσότερο από υπέροχο, εξαιρετικό και χρήσιμοοοο.',
                    'es' => 'Honestamente más que maravilloso, excelente y úuuutil.',
                    'fr' => 'Honnêtement plus que merveilleux, excellent et uuuutile.',
                    'it' => 'Onestamente più che meraviglioso, eccellente e uuuutile.',
                    'ja' => '正直なところ、素晴らしい、優れた、そして役立つ以上のものです。',
                    'ko' => '솔직히 훌륭하고 뛰어나며 유용합니다.',
                    'nl' => 'Eerlijk gezegd meer dan geweldig, uitstekend en nuuuuttig.',
                    'pl' => 'Szczerze mówiąc więcej niż wspaniały, doskonały i użyteeeeeczny.',
                    'pt' => 'Honestamente mais do que maravilhoso, excelente e úuuutil.',
                    'ru' => 'Честно говоря, более чем замечательно, отлично и полезноооо.',
                    'tr' => 'Dürüst olmak gerekirse harikadan daha fazlası, mükemmel ve faydalıııı.',
                    'uk' => 'Чесно кажучи, більше, ніж чудово, відмінно і кориииисно.',
                    'zh' => '老实说，不仅仅是精彩，更是优秀和有用。',
                ],
            ],
            [
                'name' => 'A. Diallo',
                'rate' => 5,
                'comment' => [
                    'ar' => 'برنامج اكثر من رائع … شكرا لكم ومزيد من التقدم ان شاء الله',
                    'en' => 'A program that is more than wonderful... Thank you and more progress to come, God willing.',
                    'de' => 'Ein mehr als wunderbares Programm... Danke und weitere Fortschritte, so Gott will.',
                    'el' => 'Ένα πρόγραμμα που είναι περισσότερο από υπέροχο... Σας ευχαριστώ και περισσότερη πρόοδο στο μέλλον, Θεού θέλοντος.',
                    'es' => 'Un programa que es más que maravilloso... Gracias y más progreso por venir, si Dios quiere.',
                    'fr' => 'Un programme plus que merveilleux... Merci et plus de progrès à venir, si Dieu le veut.',
                    'it' => 'Un programma che è più che meraviglioso... Grazie e altri progressi a venire, a Dio piacendo.',
                    'ja' => '素晴らしい以上のプログラムです...ありがとうございます。神が望むなら、さらなる進歩がもたらされるでしょう。',
                    'ko' => '훌륭한 프로그램 이상입니다... 감사합니다. 신의 뜻이라면 더 많은 진전이 있을 것입니다.',
                    'nl' => 'Een programma dat meer dan geweldig is... Bedankt en meer vooruitgang in de toekomst, als God het wil.',
                    'pl' => 'Program, który jest więcej niż wspaniały... Dziękuję i więcej postępów w przyszłości, jeśli Bóg da.',
                    'pt' => 'Um programa que é mais do que maravilhoso... Obrigado e mais progressos virão, se Deus quiser.',
                    'ru' => 'Программа, которая более чем замечательна... Спасибо вам и дальнейшего прогресса, если на то будет воля Божья.',
                    'tr' => 'Harikadan da öte bir program... Teşekkür ederim ve inşallah daha fazla ilerleme kaydedilir.',
                    'uk' => 'Програма, яка є більш ніж чудовою... Дякую вам і подальшого прогресу, дасть Бог.',
                    'zh' => '一个非常棒的程序......谢谢你，愿上帝保佑，未来会有更多的进步。',
                ],
            ],
            [
                'name' => 'Naser Almasri',
                'rate' => 4,
                'comment' => [
                    'ar' => 'برنامج جيد يساعد على تعلم القراءة والتعرف على كلمات جديده',
                    'en' => 'A good program that helps in learning to read and identifying new words.',
                    'de' => 'Ein gutes Programm, das beim Lesenlernen und beim Erkennen neuer Wörter hilft.',
                    'el' => 'Ένα καλό πρόγραμμα που βοηθά στην εκμάθηση της ανάγνωσης και στην αναγνώριση νέων λέξεων.',
                    'es' => 'Un buen programa que ayuda a aprender a leer y a identificar nuevas palabras.',
                    'fr' => 'Un bon programme qui aide à apprendre à lire et à identifier de nouveaux mots.',
                    'it' => 'Un buon programma che aiuta a imparare a leggere e a identificare nuove parole.',
                    'ja' => '読書を学び、新しい単語を特定するのに役立つ優れたプログラムです。',
                    'ko' => '읽기를 배우고 새로운 단어를 식별하는 데 도움이 되는 좋은 프로그램입니다.',
                    'nl' => 'Een goed programma dat helpt bij het leren lezen en het identificeren van nieuwe woorden.',
                    'pl' => 'Dobry program, który pomaga w nauce czytania i identyfikowaniu nowych słów.',
                    'pt' => 'Um bom programa que ajuda a aprender a ler e a identificar novas palavras.',
                    'ru' => 'Хорошая программа, которая помогает в обучении чтению и определении новых слов.',
                    'tr' => 'Okumayı öğrenmeye ve yeni kelimeleri tanımaya yardımcı olan iyi bir program.',
                    'uk' => 'Хороша програма, яка допомагає навчитися читати та визначати нові слова.',
                    'zh' => '一个有助于学习阅读和识别新单词的好程序。',
                ],
            ],
            [
                'name' => 'ام حسين عبدالناصر',
                'rate' => 5,
                'comment' => [
                    'ar' => 'جميل جدا ومفيدا وفيه افكار جديدة غير عن كل التطبيقات الي اعرفها تطبيق مميز وررررائع',
                    'en' => 'Very beautiful and useful, and it has new ideas unlike all the applications I know. A distinctive and wonderful application.',
                    'de' => 'Sehr schön und nützlich, und es hat neue Ideen, anders als alle Anwendungen, die ich kenne. Eine unverwechselbare und wunderbare Anwendung.',
                    'el' => 'Πολύ όμορφο και χρήσιμο, και έχει νέες ιδέες σε αντίθεση με όλες τις εφαρμογές που ξέρω. Μια ξεχωριστή και υπέροχη εφαρμογή.',
                    'es' => 'Muy bonito y útil, y tiene nuevas ideas a diferencia de todas las aplicaciones que conozco. Una aplicación distintiva y maravillosa.',
                    'fr' => 'Très beau et utile, et il a de nouvelles idées contrairement à toutes les applications que je connais. Une application distinctive et merveilleuse.',
                    'it' => 'Molto bello e utile, e ha nuove idee a differenza di tutte le applicazioni che conosco. Un\'applicazione distintiva e meravigliosa.',
                    'ja' => '私が知っているすべてのアプリケーションとは異なり、非常に美しく便利で、新しいアイデアがあります。独特で素晴らしいアプリケーションです。',
                    'ko' => '내가 아는 모든 응용 프로그램과 달리 매우 아름답고 유용하며 새로운 아이디어가 있습니다. 독특하고 훌륭한 응용 프로그램입니다.',
                    'nl' => 'Erg mooi en nuttig, en het heeft nieuwe ideeën in tegenstelling tot alle applicaties die ik ken. Een onderscheidende en prachtige applicatie.',
                    'pl' => 'Bardzo piękna i użyteczna, i ma nowe pomysły w przeciwieństwie do wszystkich aplikacji, które znam. Wyróżniająca się i wspaniała aplikacja.',
                    'pt' => 'Muito bonito e útil, e tem novas ideias ao contrário de todas as aplicações que conheço. Uma aplicação distinta e maravilhosa.',
                    'ru' => 'Очень красиво и полезно, и в нем есть новые идеи, в отличие от всех приложений, которые я знаю. Отличное и замечательное приложение.',
                    'tr' => 'Çok güzel ve kullanışlı ve bildiğim tüm uygulamalardan farklı olarak yeni fikirlere sahip. Farklı ve harika bir uygulama.',
                    'uk' => 'Дуже красиво і корисно, і в ньому є нові ідеї, на відміну від усіх програм, які я знаю. Виразна і чудова програма.',
                    'zh' => '非常漂亮和有用，它有新颖的想法，不同于我所知道的所有应用程序。一个独特而出色的应用程序。',
                ],
            ],
            [
                'name' => 'آبو الآسد',
                'rate' => 5,
                'comment' => [
                    'ar' => 'اكثر من رائع يستاهل ٥ نجوم',
                    'en' => 'More than wonderful, deserves 5 stars.',
                    'de' => 'Mehr als wunderbar, verdient 5 Sterne.',
                    'el' => 'Περισσότερο από υπέροχο, αξίζει 5 αστέρια.',
                    'es' => 'Más que maravilloso, merece 5 estrellas.',
                    'fr' => 'Plus que merveilleux, mérite 5 étoiles.',
                    'it' => 'Più che meraviglioso, merita 5 stelle.',
                    'ja' => '素晴らしい以上、5つ星に値します。',
                    'ko' => '훌륭 이상이며, 별 5개를 받을 자격이 있습니다.',
                    'nl' => 'Meer dan geweldig, verdient 5 sterren.',
                    'pl' => 'Więcej niż wspaniały, zasługuje na 5 gwiazdek.',
                    'pt' => 'Mais do que maravilhoso, merece 5 estrelas.',
                    'ru' => 'Более чем замечательно, заслуживает 5 звезд.',
                    'tr' => 'Harikadan da öte, 5 yıldızı hak ediyor.',
                    'uk' => 'Більше, ніж чудово, заслуговує на 5 зірок.',
                    'zh' => '非常棒，值得5星。',
                ],
            ],
            [
                'name' => 'نون٧٢٣',
                'rate' => 5,
                'comment' => [
                    'ar' => 'جدا جدا جميل حلال فيه كل ريال بعد التحديث الجديد اللي يشمل وضع اسئله لتأكيد فهم القصه وكمان تعديل اللكنه اليه ولا بشريه بريطانيه ولا انجليزيه قرأتي اتحسنت كثير بعد الله منه شكرا لكم وشكرا لصاحب التطبيق.',
                    'en' => 'Very, very beautiful, worth every riyal. After the new update that includes adding questions to confirm understanding of the story, and also adjusting the accent, whether automatic or human, British or English, my reading has improved a lot, thanks to God. Thank you and thanks to the owner of the application.',
                    'de' => 'Sehr, sehr schön, jeden Riyal wert. Nach dem neuen Update, das das Hinzufügen von Fragen zur Bestätigung des Verständnisses der Geschichte und auch die Anpassung des Akzents, ob automatisch oder menschlich, britisch oder englisch, beinhaltet, hat sich mein Lesen sehr verbessert, Gott sei Dank. Danke und danke an den Besitzer der Anwendung.',
                    'el' => 'Πολύ, πολύ όμορφο, αξίζει κάθε ριάλ. Μετά τη νέα ενημέρωση που περιλαμβάνει την προσθήκη ερωτήσεων για την επιβεβαίωση της κατανόησης της ιστορίας, καθώς και την προσαρμογή της προφοράς, είτε αυτόματης είτε ανθρώπινης, βρετανικής ή αγγλικής, η ανάγνωσή μου έχει βελτιωθεί πολύ, δόξα τω Θεώ. Σας ευχαριστώ και ευχαριστώ τον ιδιοκτήτη της εφαρμογής.',
                    'es' => 'Muy, muy hermoso, vale cada rial. Después de la new actualización que incluye agregar preguntas para confirmar la comprensión de la historia, y también ajustar el acento, ya sea automático o humano, británico o inglés, mi lectura ha mejorado mucho, gracias a Dios. Gracias y gracias al dueño de la aplicación.',
                    'fr' => 'Très, très beau, vaut chaque riyal. Après la nouvelle mise à jour qui comprend l\'ajout de questions pour confirmer la compréhension de l\'histoire, ainsi que l\'ajustement de l\'accent, qu\'il soit automatique ou humain, britannique ou anglais, ma lecture s\'est beaucoup améliorée, grâce à Dieu. Merci et merci au propriétaire de l\'application.',
                    'it' => 'Molto, molto bello, vale ogni riyal. Dopo il nuovo aggiornamento che include l\'aggiunta di domande per confermare la comprensione della storia, e anche la regolazione dell\'accento, che sia automatico o umano, britannico o inglese, la mia lettura è migliorata molto, grazie a Dio. Grazie e grazie al proprietario dell\'applicazione.',
                    'ja' => '非常に、非常に美しく、すべてのリヤルに値します。物語の理解を確認するための質問の追加、および自動または人間、イギリスまたは英語のアクセントの調整を含む新しい更新の後、私の読書は神のおかげで大幅に向上しました。アプリケーションの所有者に感謝します。',
                    'ko' => '매우, 매우 아름답고 모든 리얄의 가치가 있습니다. 이야기의 이해를 확인하기 위한 질문 추가 및 자동 또는 인간, 영국 또는 영어 억양 조정을 포함하는 새로운 업데이트 후, 신 덕분에 제 읽기 능력이 많이 향상되었습니다. 응용 프로그램 소유자에게 감사합니다.',
                    'nl' => 'Heel, heel mooi, elke riyal waard. Na de new update die het toevoegen van vragen om het begrip van het verhaal te bevestigen omvat, en ook het aanpassen van het accent, of het nu automatisch of menselijk, Brits of Engels is, is mijn lezen veel verbeterd, dankzij God. Dank u en dank aan de eigenaar van de applicatie.',
                    'pl' => 'Bardzo, bardzo piękne, warte każdego riala. Po new aktualizacji, która obejmuje dodawanie pytań w celu potwierdzenia zrozumienia historii, a także dostosowanie akcentu, czy to automatycznego, czy ludzkiego, brytyjskiego czy angielskiego, moje czytanie bardzo się poprawiło, dzięki Bogu. Dziękuję i dziękuję właścicielowi aplikacji.',
                    'pt' => 'Muito, muito bonito, vale cada rial. Após a nova atualização que inclui a adição de perguntas para confirmar a compreensão da história, e também o ajuste do sotaque, seja automático ou humano, britânico ou inglês, minha leitura melhorou muito, graças a Deus. Obrigado e obrigado ao proprietário da aplicação.',
                    'ru' => 'Очень, очень красиво, стоит каждого риала. После нового обновления, которое включает добавление вопросов для подтверждения понимания истории, а также настройку акцента, будь то автоматический или человеческий, британский или английский, мое чтение значительно улучшилось, слава Богу. Спасибо вам и спасибо владельцу приложения.',
                    'tr' => 'Çok, çok güzel, her riyale değer. Hikayenin anlaşılmasını teyit etmek için soru eklemeyi ve ayrıca aksanı, ister otomatik ister insan, İngiliz veya İngiliz olsun, ayarlamayı içeren yeni güncellemeden sonra okumam Tanrı\'ya şükür çok gelişti. Teşekkür ederim ve uygulamanın sahibine teşekkür ederim.',
                    'uk' => 'Дуже, дуже красиво, варте кожного ріала. Після нового оновлення, яке включає додавання запитань для підтвердження розуміння історії, а також налаштування акценту, будь то автоматичний чи людський, британський чи англійський, моє читання значно покращилося, дякувати Богу. Дякую вам і дякую власнику програми.',
                    'zh' => '非常非常漂亮，值得每一里亚尔。在新更新之后，其中包括添加问题以确认对故事的理解，以及调整口音，无论是自动的还是人工的，英国的还是英语的，我的阅读能力在上帝的帮助下提高了很多。谢谢你，也谢谢应用程序的所有者。',
                ],
            ],
            [
                'name' => 'koalacx',
                'rate' => 5,
                'comment' => [
                    'ar' => 'انصح فيه وبشدة تطبيق ممتع بشكل كبير الصراحة استفدت منه واستمتعت جدا اشكركم جداا',
                    'en' => 'I highly recommend it, a very enjoyable application. Honestly, I benefited from it and enjoyed it very much. Thank you very much.',
                    'de' => 'Ich kann es nur wärmstens empfehlen, eine sehr unterhaltsame Anwendung. Ehrlich gesagt, habe ich davon profitiert und es sehr genossen. Vielen Dank.',
                    'el' => 'Το συνιστώ ανεπιφύλακτα, μια πολύ ευχάριστη εφαρμογή. Ειλικρινά, ωφελήθηκα από αυτό και το απόλαυσα πάρα πολύ. Σας ευχαριστώ πολύ.',
                    'es' => 'Lo recomiendo encarecidamente, una aplicación muy agradable. Honestamente, me beneficié de ella y la disfruté mucho. Muchas gracias.',
                    'fr' => 'Je le recommande vivement, une application très agréable. Honnêtement, j\'en ai profité et j\'ai beaucoup apprécié. Merci beaucoup.',
                    'it' => 'Lo consiglio vivamente, un\'applicazione molto piacevole. Onestamente, ne ho tratto beneficio e mi è piaciuto molto. Grazie mille.',
                    'ja' => '非常にお勧めです、非常に楽しいアプリケーションです。正直なところ、私はそれから恩恵を受け、非常に楽しんでいました。どうもありがとうございました。',
                    'ko' => '적극 추천합니다. 매우 즐거운 응용 프로그램입니다. 솔직히, 저는 그것으로부터 혜택을 받았고 매우 즐겼습니다. 대단히 감사합니다.',
                    'nl' => 'Ik raad het ten zeerste aan, een zeer plezierige applicatie. Eerlijk gezegd heb ik ervan geprofiteerd en er erg van genoten. Heel erg bedankt.',
                    'pl' => 'Gorąco polecam, bardzo przyjemna aplikacja. Szczerze mówiąc, skorzystałem z niej i bardzo mi się podobało. Dziękuję bardzo.',
                    'pt' => 'Eu recomendo fortemente, uma aplicação muito agradável. Honestamente, eu beneficiei dela e gostei muito. Muito obrigado.',
                    'ru' => 'Я настоятельно рекомендую это, очень приятное приложение. Честно говоря, я извлек из этого пользу и мне это очень понравилось. Большое спасибо.',
                    'tr' => 'Şiddetle tavsiye ederim, çok keyifli bir uygulama. Dürüst olmak gerekirse, ondan faydalandım ve çok keyif aldım. Çok teşekkür ederim.',
                    'uk' => 'Я настійно рекомендую це, дуже приємний додаток. Чесно кажучи, я отримав від цього користь і мені це дуже сподобалося. Велике спасибі.',
                    'zh' => '我强烈推荐它，一个非常愉快的应用程序。老实说，我从中受益匪浅，非常喜欢它。非常感谢。',
                ],
            ],
            [
                'name' => 'alyaa77',
                'rate' => 5,
                'comment' => [
                    'ar' => 'من اروع التطبيقات التعليميه تطبيق ممتاز حسن اللغه عندي كثير الفكره بطله',
                    'en' => 'One of the most wonderful educational applications. An excellent application that has improved my language a lot. The idea is brilliant.',
                    'de' => 'Eine der wunderbarsten Bildungsanwendungen. Eine ausgezeichnete Anwendung, die meine Sprache sehr verbessert hat. Die Idee ist brillant.',
                    'el' => 'Μία από τις πιο υπέροχες εκπαιδευτικές εφαρμογές. Μια εξαιρετική εφαρμογή που έχει βελτιώσει πολύ τη γλώσσα μου. Η ιδέα είναι εξαιρετική.',
                    'es' => 'Una de las aplicaciones educativas más maravillosas. Una excelente aplicación que ha mejorado mucho mi idioma. La idea es brillante.',
                    'fr' => 'L\'une des plus merveilleuses applications éducatives. Une excellente application qui a beaucoup amélioré ma langue. L\'idée est brillante.',
                    'it' => 'Una delle più meravigliose applicazioni educative. Un\'eccellente applicazione che ha migliorato molto la mia lingua. L\'idea è brillante.',
                    'ja' => '最も素晴らしい教育アプリケーションの1つ。私の言語を大幅に向上させた優れたアプリケーション。アイデアは素晴らしいです。',
                    'ko' => '가장 훌륭한 교육 응용 프로그램 중 하나입니다. 내 언어를 많이 향상시킨 훌륭한 응용 프로그램입니다. 아이디어가 훌륭합니다.',
                    'nl' => 'Een van de meest prachtige educatieve toepassingen. Een uitstekende toepassing die mijn taal veel heeft verbeterd. Het idee is briljant.',
                    'pl' => 'Jedna z najwspanialszych aplikacji edukacyjnych. Doskonała aplikacja, która bardzo poprawiła mój język. Pomysł jest genialny.',
                    'pt' => 'Uma das mais maravilhosas aplicações educacionais. Uma excelente aplicação que melhorou muito a minha língua. A ideia é brilhante.',
                    'ru' => 'Одно из самых замечательных образовательных приложений. Отличное приложение, которое значительно улучшило мой язык. Идея блестящая.',
                    'tr' => 'En harika eğitim uygulamalarından biri. Dilimi çok geliştiren mükemmel bir uygulama. Fikir harika.',
                    'uk' => 'Один з найчудовіших освітніх додатків. Відмінний додаток, який значно покращив мою мову. Ідея геніальна.',
                    'zh' => '最精彩的教育应用程序之一。一个极好的应用程序，大大提高了我的语言水平。这个想法很棒。',
                ],
            ],
            [
                'name' => 'razanmunif',
                'rate' => 5,
                'comment' => [
                    'ar' => 'تطبيق سهل الاستخدام وميزة التذكير الموجودة في التطبيق خلتني استمر أكمل عليه في التعليم وتحسين مفرداتي??',
                    'en' => 'An easy-to-use application, and the reminder feature in the app made me continue with it for learning and improving my vocabulary??',
                    'de' => 'Eine einfach zu bedienende Anwendung, und die Erinnerungsfunktion in der App hat mich dazu gebracht, damit weiter zu lernen und meinen Wortschatz zu verbessern??',
                    'el' => 'Μια εύχρηστη εφαρμογή, και η λειτουργία υπενθύμισης στην εφαρμογή με έκανε να συνεχίσω με αυτήν για να μάθω και να βελτιώσω το λεξιλόγιό μου??',
                    'es' => 'Una aplicación fácil de usar, y la función de recordatorio en la aplicación me hizo continuar con ella para aprender y mejorar mi vocabulario??',
                    'fr' => 'Une application facile à utiliser, et la fonction de rappel dans l\'application m\'a fait continuer avec elle pour apprendre et améliorer mon vocabulaire??',
                    'it' => 'Un\'applicazione facile da usare, e la funzione di promemoria nell\'app mi ha fatto continuare ad usarla per imparare e migliorare il mio vocabolario??',
                    'ja' => '使いやすいアプリケーションで、アプリのリマインダー機能のおかげで、学習と語彙の向上を続けることができました??',
                    'ko' => '사용하기 쉬운 응용 프로그램이며 앱의 알림 기능 덕분에 학습과 어휘 향상을 계속할 수 있었습니다??',
                    'nl' => 'Een eenvoudig te gebruiken applicatie, en de herinneringsfunctie in de app zorgde ervoor dat ik ermee doorging om te leren en mijn woordenschat te verbeteren??',
                    'pl' => 'Łatwa w użyciu aplikacja, a funkcja przypomnienia w aplikacji sprawiła, że kontynuowałem naukę i poprawę słownictwa??',
                    'pt' => 'Uma aplicação fácil de usar, e a funcionalidade de lembrete na aplicação fez-me continuar com ela para aprender e melhorar o meu vocabulário??',
                    'ru' => 'Простое в использовании приложение, а функция напоминания в приложении заставила меня продолжать учиться и улучшать свой словарный запас??',
                    'tr' => 'Kullanımı kolay bir uygulama ve uygulamadaki hatırlatma özelliği, öğrenmeye ve kelime dağarcığımı geliştirmeye devam etmemi sağladı??',
                    'uk' => 'Простий у використанні додаток, а функція нагадування в додатку змусила мене продовжувати вчитися та покращувати свій словниковий запас??',
                    'zh' => '一个易于使用的应用程序，应用程序中的提醒功能让我继续用它来学习和提高我的词汇量？？',
                ],
            ],
        ]);

        $uniqueReviews = $reviews->unique('name');

        foreach ($uniqueReviews as $reviewData) {
            // Using updateOrCreate to prevent duplicates on re-seeding
            Review::updateOrCreate(
                ['name' => $reviewData['name']],
                $reviewData
            );
        }
    }
}
